name: "Build and Test"

on:
  pull_request:
    branches: ['master', '3_0_x-fixes', '2_4_x-fixes', '2_3_x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v3.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B
    env: 
       MAVEN_OPTS: "-Xmx1024M"
