name: "Build and Test"

on:
  pull_request:
    branches: ['master', '3_0_x-fixes', '2_4_x-fixes', '2_3_x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v3.5.0
      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B
    env: 
       MAVEN_OPTS: "-Xmx1024M"
